name= input("What is your name?")
print("")
print(f"hello(name) and welcome to CT8")
print("today we will tell a story of you want to help is")
("")
("")
location = input("Now pick your favorite  place in the world")
print("")
animal = input("pick your favorite animal")
print("")
Time_of_year = input ("what is your favorite time you year")
print("")
print("Ok now that we know some of your favorite things we can can  a story out of what you told us")
print("would you like to see the story that we made for you?")
print(f"One)day,a {animal} wandered into {location}")
print("well we are thinking of the story, what is your favorite story?")
